DROP TABLE IF EXISTS T_CONTACT;

CREATE TABLE T_CONTACT (
  ID BIGINT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250 CHAR) NOT NULL,
  URL VARCHAR(250 CHAR) NOT NULL,
  CREATE_TIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CREATE_USER_ID CHAR(8 CHAR) NOT NULL,
  UPDATE_TIME TIMESTAMP(6) NOT NULL,
  UPDATE_USER_ID CHAR(8 CHAR) NOT NULL
);